// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:140729895728:android:ee0c130ef1976d8ba216f5',
    messagingSenderId: '140729895728',
    projectId: 'sea-shop',
    databaseURL: 'https://sea-shop-default-rtdb.firebaseio.com',
    storageBucket: 'sea-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:140729895728:ios:3fb47541737ffd64a216f5',
    messagingSenderId: '140729895728',
    projectId: 'sea-shop',
    databaseURL: 'https://sea-shop-default-rtdb.firebaseio.com',
    storageBucket: 'sea-shop.appspot.com',
    androidClientId:
        '140729895728-2b8p1d33ui3ejkj7ar11aaheussg2044.apps.googleusercontent.com',
    iosClientId:
        '140729895728-kod0k253bbcmbsfibfmougtb3mpc4o6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.seaShop',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:140729895728:web:fba341546eb3f4a5a216f5',
    messagingSenderId: '140729895728',
    projectId: 'sea-shop',
    authDomain: 'sea-shop.firebaseapp.com',
    databaseURL: 'https://sea-shop-default-rtdb.firebaseio.com',
    storageBucket: 'sea-shop.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:140729895728:ios:3fb47541737ffd64a216f5',
    messagingSenderId: '140729895728',
    projectId: 'sea-shop',
    databaseURL: 'https://sea-shop-default-rtdb.firebaseio.com',
    storageBucket: 'sea-shop.appspot.com',
    androidClientId:
        '140729895728-2b8p1d33ui3ejkj7ar11aaheussg2044.apps.googleusercontent.com',
    iosClientId:
        '140729895728-kod0k253bbcmbsfibfmougtb3mpc4o6f.apps.googleusercontent.com',
    iosBundleId: 'com.example.seaShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:140729895728:web:4fef7b5121924cc1a216f5',
    messagingSenderId: '140729895728',
    projectId: 'sea-shop',
    authDomain: 'sea-shop.firebaseapp.com',
    databaseURL: 'https://sea-shop-default-rtdb.firebaseio.com',
    storageBucket: 'sea-shop.appspot.com',
  );
}
